### ISSUE TITLE
Witness service constructs correct empty tx witness for block circuit

### ISSUE THREAD

**Issue by lightning-li** [bnb-chain/zkbnb#203]
**Describe the Issue**
See the block circuit here: https://github.com/bnb-chain/zkbnb-crypto/issues/46

**To Reproduce**
N/A

**Expected behavior**
Witness service constructs correct empty tx witness for block circuit as follows:
- when calling `EmptyTx(stateRoot[]byte)` function, pass new `StateRoot` which generated by applying previous non-empty tx.

**Comment by yutianwu** [comment]
https://github.com/bnb-chain/zkbnb/pull/205 fixed in this pr, will close it.
